#!/usr/bin/env python3
"""Builds the native executable from your own copy of the game.

This script is the bench's only entry point. It produces the three generated
files -- the translated code, the dispatch table, the description of the disc --
then compiles. Nothing it writes is under version control: it is the game's
code and data in another notation, exactly like `asm/`.

    python3 tools/m0/build.py PSX.EXE --iso data.iso --compile
    ./build/m0 90 PSX.EXE

`data.iso` is the image of your disc's data track. It serves the sectors as
they are: the game finds its volume descriptor, its directory and its files
there, without anyone having to extract them.

Why a script and not a Makefile
-------------------------------
The list of functions to translate is not written down anywhere: it is derived
from the disassembly, which is itself derived from the executable. A Makefile
would require freezing that list into a file, which would go stale on the first
renamed symbol. Here it is recomputed on every build.
"""
import argparse
import os
import re
import struct
import shutil
import subprocess
import sys

INTERNAL_ENTRIES = {"irq_body": 0x8004934C}

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import recomp


def asm_units():
    """The disassembly files, in the order splat writes them."""
    dir = os.path.join(ROOT, "asm")
    if not os.path.isdir(dir):
        sys.exit("asm/ is missing -- run `make setup` first")
    return [os.path.join(dir, n)
            for n in sorted(os.listdir(dir)) if n.endswith(".s")]


def functions(paths):
    """Every `glabel` with its address and its instruction count.

    We keep the first definition encountered: the same symbol can appear in two
    units when a boundary has moved, and the second one is then nothing but a
    duplicate."""
    seen = {}
    order = []
    pattern = re.compile(r"/\* [0-9A-F]+ ([0-9A-F]{8}) [0-9A-F]{8} \*/")
    for path in paths:
        txt = open(path, encoding="utf-8", errors="replace").read()
        for block in re.split(r"^glabel ", txt, flags=re.M)[1:]:
            name = block.split("\n", 1)[0].strip()
            if name in seen:
                continue
            ins = pattern.findall(block.split("\nglabel ")[0])
            if not ins:
                continue
            seen[name] = (int(ins[0], 16), len(ins))
            order.append(name)
    return order, seen


def exe_header(path):
    with open(path, "rb") as f:
        h = f.read(0x800)
    if h[:8] != b"PS-X EXE":
        sys.exit(path + " is not a PlayStation executable")
    pc, = struct.unpack_from("<I", h, 0x10)
    load, = struct.unpack_from("<I", h, 0x18)
    size, = struct.unpack_from("<I", h, 0x1C)
    return pc, load, size


def write_game(exe, dest):
    """Translates everything, and returns the list of functions actually defined."""
    pc, load, size = exe_header(exe)
    paths = asm_units()
    recomp.load_symbols(*paths)
    names, table = functions(paths)

    # The entry point has no label: it is written as raw data in the unit that
    # contains it. We take it from the header, and bound it with the first
    # known function that follows it.
    following = sorted(a for a, _ in table.values() if a > pc)
    end = following[0] if following else pc + 256
    table["_start"] = (pc, (end - pc) // 4)
    recomp.SYMS[pc] = "_start"
    names.insert(0, "_start")

    # The body of the BIOS interrupt handler. It is entered through the middle
    # of its function: the prologue installs a context once and for all, and
    # replaying it on every interrupt was erasing the CD driver's state. It is
    # the only entry point in the binary that is not a function entry, and so
    # it is declared here rather than guessed.
    for name, addr in INTERNAL_ENTRIES.items():
        owner = max((a, n) for a, n in table.values() if a <= addr)
        left = (owner[0] + 4 * owner[1] - addr) // 4
        if left <= 0:
            continue
        table[name] = (addr, left)
        names.append(name)

    out = ['/* generated by tools/m0/build.py -- do not check in */',
           '#include "rt.h"', '#include "gte.h"',
           "u32 psx_dispatch(u32,u32,u32,u32,u32,u32);"]
    defined, stubs = [], []
    for name in names:
        addr, n = table[name]
        words = recomp.words_from_exe(exe, addr, n, load=load, off=0x800)
        try:
            out.append(recomp.translate("psx_" + name, addr, words))
        except recomp.Unsupported as e:
            # A function the translator refuses becomes a stub that announces
            # itself. Silence costs a great deal here: it was a mute stub on
            # InitGeom that made the whole track disappear for a day, five
            # functions further along.
            stubs.append((name, str(e)))
            out.append('u32 psx_%s(u32 a, u32 b, u32 c, u32 d)\n'
                       '{ extern void stub_hit(const char *); '
                       'stub_hit("%s"); return 0; }' % (name, name))
        if name not in INTERNAL_ENTRIES:
            defined.append((addr, name))
    open(dest, "w").write("\n".join(out) + "\n")
    return defined, stubs


def write_table(defined, dest):
    """The address -> function table, sorted: the dispatcher reads it by binary
    search, and an indirect call is a frequent thing."""
    defined = sorted(set(defined))
    out = ['/* generated by tools/m0/build.py -- do not check in */',
           '#include "rt.h"']
    for _, name in defined:
        out.append("u32 psx_%s(u32,u32,u32,u32);" % name)
    out.append("const struct { u32 a; u32 (*f)(u32,u32,u32,u32); } PSX_FUNCS[] = {")
    for addr, name in defined:
        out.append("  {0x%08Xu, psx_%s}," % (addr, name))
    out.append("};")
    out.append("const int PSX_NFUNCS = %d;" % len(defined))
    open(dest, "w").write("\n".join(out) + "\n")
    return len(defined)


def read_cue(path):
    """The tracks of a CUE sheet: number, type, file, starting sector.

    Absolute positions are not written in the sheet when each track has its own
    file: they are derived by accumulating the lengths, a raw sector being 2352
    bytes. INDEX 01 gives the start of the track proper, after the two seconds
    of silence the file carries."""
    dir = os.path.dirname(os.path.abspath(path))
    tracks = []
    file = None
    lba = 0
    number = typ = None
    for line in open(path, encoding="utf-8", errors="replace"):
        l = line.strip()
        if l.startswith("FILE "):
            if file:
                lba += os.path.getsize(file) // 2352
            name = l.split('"')[1] if '"' in l else l.split()[1]
            file = os.path.join(dir, name)
            if not os.path.exists(file):
                sys.exit("the sheet names a file that is not there: " + file)
        elif l.startswith("TRACK "):
            parts = l.split()
            number, typ = int(parts[1]), parts[2]
        elif l.startswith("INDEX 01") and file is not None:
            mm, ss, ff = (int(x) for x in l.split()[2].split(":"))
            offset = (mm * 60 + ss) * 75 + ff
            tracks.append({"n": number, "audio": typ == "AUDIO",
                           "file": file, "start": lba + offset,
                           "skip": offset})
    return tracks


def target_path(p, windows):
    """The path as the built program will see it at run time.

    Paths are written in absolute form: the program is launched from anywhere,
    and a relative path would make opening the disc depend on the current
    directory. But an `.exe` built from WSL will be launched by Windows, which
    does not know `/mnt/e/...` -- it would open a file that does not exist, and
    the game would complain about not finding its data with no way to tell why.
    The translation is the one WSL itself performs: /mnt/e becomes E:.
    """
    a = os.path.abspath(p)
    if not windows:
        return a
    # Built from Windows itself, the absolute path is already the right one:
    # there is nothing to translate, and translating it anyway made it relative
    # -- the program would no longer have found its disc as soon as it was
    # launched from elsewhere. A conversion rule must first be able to
    # recognise what has already been converted.
    if re.match(r"^[A-Za-z]:[\\/]", a):
        return a.replace("/", "\\")
    m = re.match(r"/mnt/([a-z])(/.*)?$", a)
    if m:
        return m.group(1).upper() + ":" + (m.group(2) or "/").replace("/", "\\")
    # Outside the mounted drives we do not know how to translate: the relative
    # path is then the only one with a chance, provided the program is launched
    # from the same directory.
    return os.path.relpath(a).replace("/", "\\")


def write_disc(iso, cue, dest, windows=False):
    """The description of the disc: the data image, and the audio tracks."""
    if iso:
        sectors = (os.path.getsize(iso) + 2047) // 2048
        path = target_path(iso, windows)
    else:
        sectors, path = 0, ""
    tracks = read_cue(cue) if cue else []
    audio = [p for p in tracks if p["audio"]]
    lines = ["/* generated by tools/m0/build.py -- do not check in */",
             "struct cdfile { unsigned int lba, size; const char *path; };",
             "const struct cdfile CDFILES[] = { {0, 0, 0} };",
             "const int NCDFILES = 0;",
             'const char *CD_META = "%s";' % path.replace("\\", "\\\\"),
             "const unsigned int CD_META_SECTORS = %u;" % sectors,
             "",
             "/* The audio tracks. `start` is their absolute sector on the",
             "   disc, `skip` the silence their file carries. */",
             "struct cdtrack { unsigned int start, length, skip; const char *file; };",
             "const struct cdtrack CDTRACKS[] = {"]
    for p in tracks:
        n = os.path.getsize(p["file"]) // 2352
        lines.append('  {%u, %u, %u, "%s"},   /* track %02d%s */'
                     % (p["start"], n, p["skip"],
                        target_path(p["file"], windows).replace("\\", "\\\\"),
                        p["n"], "" if p["audio"] else "  data"))
    lines.append("};")
    lines.append("const int NCDTRACKS = %d;" % len(tracks))
    open(dest, "w").write("\n".join(lines) + "\n")
    return sectors, len(tracks), len(audio)


def sdl_flags(prefix=None):
    """SDL2's compilation options, or None if it is not installed.

    With a prefix, nothing is asked of anyone: this is the tree SDL ships for
    MinGW (`SDL2-x.y.z/x86_64-w64-mingw32`), which has neither pkg-config nor
    sdl2-config -- it is not installed, only unpacked.
    """
    if prefix is False:
        # Windows target without --sdl: above all do not question the host
        # machine's pkg-config, which would answer with the paths of its own
        # SDL -- headers the cross-compiler cannot read.
        return None
    if prefix:
        inc = os.path.join(prefix, "include")
        lib = os.path.join(prefix, "lib")
        if not os.path.isdir(inc):
            sys.exit("SDL2: %s does not contain include/" % prefix)
        return ["-I" + inc, "-L" + lib, "-lSDL2"]
    for tool in (["pkg-config", "--cflags", "--libs", "sdl2"],
                 ["sdl2-config", "--cflags", "--libs"]):
        try:
            r = subprocess.run(tool, capture_output=True, text=True)
            if r.returncode == 0 and r.stdout.strip():
                return r.stdout.split()
        except FileNotFoundError:
            continue
    return None


def preflight(a):
    """Say everything that is missing, before starting any work.

    Translating nine hundred and forty-nine functions takes a minute. Finding
    out afterwards that there is no compiler, through a "command not found"
    from the system, is a minute wasted and a message that does not say what to
    do. So we look first, and return the whole list: whoever installs three
    things at once does not come back three times.
    """
    missing, notes = [], []

    if not os.path.exists(a.exe):
        missing.append(
            "%s cannot be found.\n"
            "   This is your own copy of the game's executable, taken from your\n"
            "   own disc (SLPS-00001). Nothing here replaces it." % a.exe)

    if not os.path.isdir(os.path.join(ROOT, "asm")):
        missing.append(
            "asm/ is missing: the disassembly has not been produced yet.\n"
            "   make setup            # once, after cloning")

    if not shutil.which(a.cc):
        what = ("sudo apt install gcc-mingw-w64-x86-64" if a.windows
                else "sudo apt install build-essential")
        missing.append("the compiler %s is not on the path.\n"
                       "   %s" % (a.cc, what))

    for flag, path in (("--iso", a.iso), ("--cue", a.cue)):
        if path and not os.path.exists(path):
            missing.append("%s %s: this file does not exist." % (flag, path))

    if a.sdl:
        if not os.path.isdir(os.path.join(a.sdl, "include")):
            missing.append(
                "--sdl %s does not contain include/.\n"
                "   Expected: the root SDL ships for MinGW, the one that\n"
                "   carries include/, lib/ and bin/ -- SDL2-x.y.z/x86_64-w64-mingw32,\n"
                "   and not the directory that contains it." % a.sdl)
        elif not os.path.exists(os.path.join(a.sdl, "bin", "SDL2.dll")):
            notes.append("SDL2.dll is missing from %s/bin: it will have to be put\n"
                         "   next to the program by hand, otherwise Windows will\n"
                         "   not start it." % a.sdl)
    elif a.windows:
        notes.append("without --sdl, the .exe will have neither window nor sound.\n"
                     "   curl -LO https://github.com/libsdl-org/SDL/releases/"
                    "download/release-2.30.9/SDL2-devel-2.30.9-mingw.tar.gz\n"
                     "   tar xzf SDL2-devel-2.30.9-mingw.tar.gz\n"
                     "   then --sdl SDL2-2.30.9/x86_64-w64-mingw32")

    if not a.iso:
        notes.append("without --iso, the game starts then stops at loading:\n"
                     "   it reads its files from the disc, not from the executable.")
    if not a.cue:
        notes.append("without --cue, no music: the twelve tracks are ordinary\n"
                     "   audio tracks, burned next to the data.")

    for m in notes:
        print("note: " + m)
    if missing:
        print("\n%d thing%s missing before this can build:\n"
              % (len(missing), "s" if len(missing) > 1 else ""))
        for m in missing:
            print(" * " + m + "\n")
        sys.exit(1)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("exe", help="your copy of PSX.EXE")
    p.add_argument("--iso", help="image of the disc's data track")
    p.add_argument("--cue", help="the disc's CUE sheet, for the music")
    p.add_argument("--out", default=os.path.join(ROOT, "build", "m0"),
                   help="output directory (default: build/m0)")
    p.add_argument("--compile", action="store_true", help="compile afterwards")
    p.add_argument("--cc", default=None)
    p.add_argument("--windows", action="store_true",
                   help="produce a Windows .exe (MinGW cross-compiler)")
    p.add_argument("--sdl", help="root of SDL2 for MinGW "
                                 "(SDL2-x.y.z/x86_64-w64-mingw32)")
    a = p.parse_args()
    if not a.cc:
        a.cc = "x86_64-w64-mingw32-gcc" if a.windows else "gcc"

    preflight(a)

    os.makedirs(a.out, exist_ok=True)
    defined, stubs = write_game(a.exe, os.path.join(a.out, "game.c"))
    n = write_table(defined, os.path.join(a.out, "table.c"))
    sectors, ntracks, naudio = write_disc(a.iso, a.cue,
                                          os.path.join(a.out, "cdfiles.c"),
                                          a.windows)
    open(os.path.join(a.out, "ram.c"), "w").write(
        "unsigned char RAM[0x200000];\nunsigned int g_sp;\n")

    print("%d functions translated" % n)
    if stubs:
        print("%d stubs:" % len(stubs))
        for name, reason in stubs:
            print("   %-24s %s" % (name, reason))
    else:
        print("no stubs")
    if a.iso:
        print("disc: %s, %d sectors" % (a.iso, sectors))
    else:
        print("disc: none (--iso missing) -- the game will stop at loading")
    if ntracks:
        print("tracks: %d of which %d audio" % (ntracks, naudio))
    else:
        print("tracks: none (--cue missing) -- no music")

    sources = [os.path.join(HERE, f)
               for f in ("main.c", "hw.c", "gpu.c", "gte.c", "video.c", "audio.c", "spu.c", "mods.c")]
    sources += [os.path.join(a.out, f) for f in ("game.c", "table.c", "cdfiles.c", "ram.c")]
    binary = os.path.join(a.out, "m0.exe" if a.windows else "m0")
    cmd = [a.cc, "-O1", "-w", "-fcommon", "-I", HERE, "-o", binary]
    if a.windows:
        # The translated code makes a single object of nine hundred and
        # forty-nine functions; Windows's object format counts its sections in
        # sixteen bits and overflows well before that. -mbig-obj lifts the
        # limit.
        cmd += ["-Wa,-mbig-obj"]
    cmd += sources

    # SDL2 is optional: without it the bench writes frames to disc and reads a
    # script, as before. With it, a window and a keyboard.
    sdl = sdl_flags(a.sdl or (False if a.windows else None))
    if sdl:
        cmd += ["-DWITH_SDL"] + sdl
        print("SDL2 found: the game will open in a window")
    else:
        print("SDL2 missing: no window (frames on disc and a script)")
        if a.windows:
            print("   --sdl SDL2-x.y.z/x86_64-w64-mingw32  (SDL2-devel-*-mingw.tar.gz)")
        else:
            print("   on Debian or Ubuntu:  sudo apt install libsdl2-dev")
    if a.compile:
        print("compiling...")
        r = subprocess.run(cmd)
        if r.returncode:
            sys.exit(r.returncode)
        # Windows does not look for libraries on a system path: the DLL must be
        # next to the program, otherwise it does not start at all.
        if a.windows and a.sdl:
            import shutil
            dll = os.path.join(a.sdl, "bin", "SDL2.dll")
            if os.path.exists(dll):
                shutil.copy(dll, a.out)
                print("   SDL2.dll copied next to the program")
        print("=> %s" % binary)
        print("   %s 90 %s" % (binary, a.exe))
    else:
        print("\n" + " ".join(cmd))


if __name__ == "__main__":
    main()
